SynBioDex/SBOLExplorer

- flask/.travis.yml
- flask/docker/Dockerfile
- flask/docker/Dockerfile-synbiohub
- flask/docker/config-synbiohub.json
This pull request makes a few changes to the Docker configuration:
- persists the explorer dumps and the configuration across images '
- creates a separate image that can be used in compose that automatically knows where to find the expected endpoints (compose means you can't use localhost) 
- Autobuilds the docker images and pushes them to hub. Michael would have to add his credentials for DockerHub in TravisCI
> Docker changes 

- flask/query.py
- flask/utils.py
Improves error handling by wrapping all requests in try/catch and recovering where possible.
> Better error handling

- flask/cluster.py
File can now detect whether the user is on OSX or Linux, and grab the correct usearch file
> Added OS detecting capabilities

- flask/cluster.py
- flask/explorer.py
- flask/search.py
- flask/sequencesearch.py
Created endpoint to handle sequence searching, also allows SPARQL query from SynBioHub to be processed.
> Added sequence searching functionality

- flask/cluster.py
- flask/explorer.py
- flask/search.py
- flask/sequencesearch.py
Added safeguard against config file with no "which_search option, also added functionality to go with sequence searching flags on synbiohub side.
> Fixed issue with "which_search" missing in config file

- flask/utils.py
Returns empty dict if no file is found
> Check for missing dump file

- flask/explorer.py
- flask/search.py
- flask/update.cron
- flask/utils.py
If using the SBH API, users can now get more info on their sequence search through the returned JSON.
> Add sequence search data to JSON

- flask/cluster.py
- flask/explorer.py
- flask/search.py
- flask/sequencesearch.py
Corresponds with PR on SynBioHub
> Add support for file upload when sequence searching

- flask/explorer.py
Checks if ES index exists on startup.
> Get index if none is found

- flask/explorer.py
- flask/index.py
- flask/query.py
- flask/search.py
- flask/sequencesearch.py
Added extensive error handling within SBOLExplorer's endpoints. Beginning to add documentation.
> Error handling and documentation

- flask/explorer.py
- flask/index.py
- flask/query.py
- flask/search.py
- flask/sequencesearch.py
- flask/so-simplified.json
Also added plenty of comments in the code.
> Add keywords to inverted index

- flask/config.json
- flask/explorer.py
- flask/update.cron
- flask/utils.py
Added background thread to watch for auto indexing
> Add auto indexing capabilities

- flask/explorer.py
- flask/search.py
Added sequence search scoring to pagerank, removed duplicates from search, and fixed elasticsearch crashing explorer.
> Search upgrades

- flask/index.py
- flask/query.py
Get graphs separately instead of in the SPARQL query with parts
> Index parts by graph seperately

- flask/cluster.py
- flask/explorer.py
- flask/index.py
- flask/pagerank.py
Add the URI prefix fetched from SBH used during indexing to check for allowed graphs.
> Improve indexing graphs

- flask/index.py
- flask/query.py
Groups all duplicate parts by role, CSV formatted.
> Add concatenation in SPARQL query

- flask/cluster.py
- flask/explorer.py
- flask/index.py
- flask/pagerank.py
- flask/query.py
This reverts commit 05a487a5c6956ba483b06f0e591f8392f71f953c, reversing
changes made to 49251b29b6a698c2e230693238ee19b5f11987c2.
This commit also adds better support for messages during indexing.
> Revert "Merge pull request #81 from SynBioDex/improve_indexing_graphs"

- flask/query.py
- flask/search.py
If string is empty, search only by ID instead.
> Add method to query by ID's only

- flask/search.py
Looks like there was some sort of catch that Michael implemented that I missed. Hitting the proper method now.
> Fix empty ES string + advanced search

- flask/search.py
> Remove duplicate filter

- flask/index.py
ID wasn't being added correctly to elasticsearch
> Fix incremental update

- flask/cluster.py
- flask/explorer.py
- flask/index.py
- flask/pagerank.py
- flask/query.py
- flask/utils.py
Delete logs if they are over 20 MB in size, and give indexing its own log file.
> Clean up logging
